sudo: false
rvm:
  - 2.1
  - 2.2
  - 2.3.0
addons:
  apt:
    packages:
      - unzip
      - libxss1
cache: bundler
notifications:
  recipients:
    - p0deje@gmail.com
    - jarmo.p@gmail.com
    - titusfortner@gmail.com
  slack:
    secure: BLsBCm33R32VNRccrLx9F0P24X6BVpVHj1OWaN4Kyn6g9qXteIwC2VKVMnKNbifpojfMkrn0OeFQFK1O1DSOsC3mgzn/udoB+DnUGcSemFUn04xhbYF5SI+3zGPKPo0JLvjjdEKSSma84YwKdrj88pGUK34p01gL8hiaqjFzWdk=
before_script:
  - mkdir travis-phantomjs
  - export PATH=$PWD/travis-phantomjs:$PATH
  - support/travis.sh
script: bundle exec rake $RAKE_TASK
env:
  - RAKE_TASK=spec:firefox
  - RAKE_TASK=spec:firefox ALWAYS_LOCATE=false
  - RAKE_TASK=spec:firefox PREFER_CSS=1 SELECTOR_STATS=1
  - RAKE_TASK=spec:chrome
  - RAKE_TASK=spec:chrome ALWAYS_LOCATE=false
  - RAKE_TASK=spec:chrome PREFER_CSS=1 SELECTOR_STATS=1
  - RAKE_TASK=spec:phantomjs
  - RAKE_TASK=spec:phantomjs ALWAYS_LOCATE=false
  - RAKE_TASK=spec:phantomjs PREFER_CSS=1 SELECTOR_STATS=1
  - RAKE_TASK=yard:doctest
