name: All Tests

on:
  - push
  - pull_request

jobs:
  documentation-test:
    name: Yard Doctest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: bundle install
      - uses: ./.github/actions/install-chrome
      - uses: ./.github/actions/setup-linux
      - run: |
          bundle exec rake yard:doctest

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.6', '2.7', '3.0']
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install
      - uses: ./.github/actions/install-chrome
      - uses: ./.github/actions/setup-linux
      - run: |
          bundle exec rake spec:unit
        env:
          DISPLAY: :99

  linter-test:
    name: Rubocop Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: bundle install
      - run: bundle exec rubocop

  local-tests:
    name: Local Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby: [ 2.6, 3.0 ]
        task: [ chrome, firefox, edge ]
        include:
          - os: 'macos-latest'
            ruby: 2.6
            task: 'safari'
          - os: 'macos-latest'
            ruby: 3.0
            task: 'safari'
          - os: 'windows-latest'
            ruby: 2.6
            task: 'ie'
          - os: 'windows-latest'
            ruby: 3.0
            task: 'ie'
        exclude:
          - os: 'ubuntu-latest'
            task: 'edge'
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-chrome
        if: |
          matrix.task == 'chrome' &&
          matrix.os == 'ubuntu-latest'
      - uses: ./.github/actions/setup-linux
        if:  matrix.os == 'ubuntu-latest'
      - uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: '93.0'
        if: matrix.task == 'firefox'
      - uses: ./.github/actions/enable-safari
        if: matrix.task == 'safari'
      - run: |
          echo "COVERAGE=true" >> $GITHUB_ENV
        if: |
          matrix.os == 'ubuntu-latest' ||
          matrix.os == 'macos-latest'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install
      - run: |
          bundle exec rake spec:${{ matrix.task }}
        env:
          DISPLAY: :99
